# playbook/sections/deploy-certmanager.yaml
---
- name: Add cert-manager chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Update helm cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    wait: true
    update_repo_cache: True
    values:
      crds: 
        enabled: true
      prometheus:
        enabled: false
      featureGates: ServerSideApply=true
  register: cert_manager

- name: Wait for cert-manager to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    name: cert-manager-webhook
    namespace: cert-manager
  register: cert_manager_webhook
  until: cert_manager_webhook.resources[0].status.readyReplicas == 1
  retries: 10
  delay: 10
  delegate_to: localhost

- name: Make configuration for cert-manager
  template:
    src: ../templates/cert-manager.yaml.j2
    dest: /tmp/cert-manager.yaml
  delegate_to: localhost

- name: Apply cert-manager configuration
  become_user: still
  kubernetes.core.k8s:
    src: /tmp/cert-manager.yaml
    state: present
    wait: true
    wait_timeout: 300
  delegate_to: localhost
